---
title: "Elise_Tick"
output: html_document
author: SAS
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

```

##Loading Packages

```{r}

library(tidyverse)
library(ggplot2)
library(lmerTest)
library(nlme)
library(lme4)
library(devtools)
library(rptR)
library(lmeresampler)
library(boot)
library(purrr)
devtools::install_github("mastoffel/rptR", build_vignettes = TRUE)

```

##WD & Loading Data

```{r}
setwd("Desktop")
tickdata<-read.csv("Tick Questing and Infection Data.csv")
tickdata

```
##Data Cleaning

```{r}

#Below was adding a row to make questing numeric 
tickdata$Numeric.Quest<-0
tickdata$Numeric.Quest[tickdata$Quested.=="Yes"]<-1
tickdata
str(tickdata)

#below making day numeric too
tickdata$Numeric.Day<-0
tickdata$Numeric.Day[tickdata$Day=="Day 1"]<-1
tickdata$Numeric.Day[tickdata$Day=="Day 2"]<-2
tickdata$Numeric.Day[tickdata$Day=="Day 3"]<-3
tickdata
str(tickdata)

TotaltimeQuesters<-subset(tickdata,Total.Time.Spent.Questing>0)
#Totaltimequesters is the data sheet without non questers (0s in total time quested)

tickdata$Total.Time.Spent.Questing<-as.numeric(tickdata$Total.Time.Spent.Questing)
str(tickdata)

```



##Basic ggplots

```{r}

ggplot(tickdata,aes(x=Day,y=Total.Time.Spent.Questing,color=Life.Stage))+geom_boxplot()
#this plot is total time but with the 0s (non questers)

ggplot(TotaltimeQuesters,aes(x=Day,y=Total.Time.Spent.Questing,color=Life.Stage))+geom_boxplot()
#plot for total time spent questing without non questers 

ggplot(TotaltimeQuesters,aes(x=Day,y=Questing.Height.Average,color=Life.Stage))+geom_boxplot()
#Questing Height average without non questers 

ggplot(TotaltimeQuesters,aes(x=Day,y=Questing.Height.Average,color=Life.Stage))+geom_boxplot()+
  scale_color_manual(values=c("purple","red"))


ggplot(TotaltimeQuesters,aes(x=Day,y=Questing.Height.Average,color=Life.Stage, fill=Life.Stage))+geom_boxplot()+
  scale_color_manual(values=c("purple","red"))+
  scale_fill_manual(values=c("yellow","blue"))
#How to change the inside colors of the boxes


ggplot(TotaltimeQuesters,aes(x=Day,y=Total.Time.Spent.Questing,group=Combined.ID))+
  (geom_line(color="red"))

ggplot(TotaltimeQuesters,aes(x=Day,y=Total.Time.Spent.Questing,group=Combined.ID))+
  (geom_line(color="red"))+facet_grid(Site~.)

```

##Checking Data Distributions

```{r}

hist(TotaltimeQuesters$Total.Time.Spent.Questing)

hist(TotaltimeQuesters$Questing.Height.Average)

```




##TRANSFORM Residuals
```{r}
#This one's residuals are bad. Transformations needed.
tickresiduals <- lm(Total.Time.Spent.Questing~Life.Stage+Infection.Status+Day, data=TotaltimeQuesters)
tickresids <- resid(tickresiduals)
plot(fitted(tickresiduals), tickresids) + abline(0,0)
qqnorm(tickresids) #+ qqline(tickresids)
plot(density(tickresids))

#This one's residuals are fine. No transformations needed.
tickresiduals2 <- lm(Questing.Height.Average~Life.Stage+Infection.Status+Day, data=TotaltimeQuesters)
tickresids2 <- resid(tickresiduals2)
plot(fitted(tickresiduals2), tickresids2) + abline(0,0)
qqnorm(tickresids2)
 qqline(tickresids2)
plot(density(tickresids2))

######
#TRANSFORMATIONS

hist(TotaltimeQuesters$Total.Time.Spent.Questing)
hist(log10(TotaltimeQuesters$Total.Time.Spent.Questing))
hist((TotaltimeQuesters$Total.Time.Spent.Questing)^(1/3))
hist(sqrt(TotaltimeQuesters$Total.Time.Spent.Questing))
hist((TotaltimeQuesters$Total.Time.Spent.Questing)^(1/4)) 

```


##Models

```{r}

Model1<-lmer(Total.Time.Spent.Questing~Life.Stage+Infection.Status+Day+(1|Combined.ID),data=TotaltimeQuesters)
summary(Model1)

Model2<-lmer(Questing.Height.Average~Life.Stage+Infection.Status+Day+(1|Combined.ID),data=TotaltimeQuesters)
summary(Model2)

Model3<-lmer(Questing.Height.Average*Total.Time.Spent.Questing~Life.Stage+Infection.Status+Day+(1|Combined.ID),data=TotaltimeQuesters)
summary(Model3)
#This was checking for the interaction but it says what we already knew from the total time one. 


Model4<-glmer(Numeric.Quest~Life.Stage+Infection.Status+Day + (1|Combined.ID),data=tickdata, family = binomial())

summary(Model4)

```

##Repeatability: Assuming Normal Distribution

```{r}



aveheightgaussian <- rpt(Questing.Height.Average~Life.Stage+Infection.Status+Numeric.Day +(1 | Combined.ID), grname = "Combined.ID", 
data = TotaltimeQuesters, datatype = "Gaussian", nboot = 1000, 
            npermut = 0)

print(aveheightgaussian)

plot(aveheightgaussian, grname = "Combined.ID", type = "boot", cex.main = 0.8)

```

##Repeatability with Binary Questers

```{r}
#without life stage
binarytick <- rpt(Numeric.Quest~  Numeric.Day +
(1 | Combined.ID), grname = "Combined.ID", 
data = tickdata, datatype = "Binary", nboot = 1000, 
            npermut = 0)

print(binarytick)

plot(binarytick, grname = "Combined.ID", type = "boot", cex.main = 0.8)

#with lifestage

binarytickls <- rpt(Numeric.Quest~  Numeric.Day + Life.Stage +
(1 | Combined.ID), grname = "Combined.ID", 
data = tickdata, datatype = "Binary", nboot = 1000, 
            npermut = 0)

print(binarytickls)

 
```

##Repeatability with Infection Status in Binary Sick Ticks
```{r}
#without life stage
binarytick <- rpt(Numeric.Quest~  Numeric.Day + Infection.Status+
(1 | Combined.ID), grname = "Combined.ID", 
data = tickdata, datatype = "Binary", nboot = 1000, 
            npermut = 0)
#also repeatable with just numeric.quest ~ infection.status
print(binarytick)

plot(binarytick, grname = "Combined.ID", type = "boot", cex.main = 0.8)

#with life stage
binarytickls <- rpt(Numeric.Quest~  Numeric.Day + Life.Stage + Infection.Status +
(1 | Combined.ID), grname = "Combined.ID", 
data = tickdata, datatype = "Binary", nboot = 1000, 
            npermut = 0)

print(binarytickls)




```



```{r}
#Splitting up dataset into infected + non-infected
tickdata$Infection.Status
tickdata$Infection.Status <- as.factor(tickdata$Infection.Status)
str(tickdata$Infection.Status)
tick_split <- split(tickdata, tickdata$Infection.Status)
tick_split$Negative #new dataset just negatives
tick_split$Positive #new dataset just positives

#checking repeatability separately for infected + not

ticksinfected <- rpt(Numeric.Quest~  Numeric.Day + Life.Stage +
(1 | Combined.ID), grname = "Combined.ID", 
data = tick_split$Positive, datatype = "Binary", nboot = 1000, 
            npermut = 0)

print(ticksinfected)

ticksNOTinfected <- rpt(Numeric.Quest~  Numeric.Day + Life.Stage +
(1 | Combined.ID), grname = "Combined.ID", 
data = tick_split$Negative, datatype = "Binary", nboot = 1000, 
            npermut = 0)

print(ticksNOTinfected)



```



##Repeatability: Assuming Nonnormal Distribution

```{r}

nonpara_boot <- function(model, bootN = 1000){
  
  # helper function for boostrap()
  my_get <- function(model) { 
    beta <- getME(model, "beta")
    sigma <- getME(model, "sigma")
    sigma2 <- sigma^2
    tau2 <- unname(sigma * getME(model, "theta"))^2
    rep <- tau2/(tau2 + sigma2)
    c(beta = beta, sigma2 = sigma2,  tau2 = tau2, rep = rep) 
  }
  
  # boostrapping - type = "case" fully
  # we are only respmpleing "individual" - resample = c(TRUE, FALSE)
  #  for why - see "Van der Leeden, R., Meijer, E. and Busing F. M. (2008) Resampling multilevel models. In J. de Leeuw and E. Meijer, editors, Handbook of Multilevel Analysis, pages 401–433. New York: Springer."
  # The book chapter says "The cases bootstrap, finally, requires minimal assumptions: Only the hierarchical dependency in the data is assumed to be specified correctly."
  boot_res <- lmeresampler::bootstrap(model = model, fn = my_get, type = "case", B = bootN, resample = c(TRUE, FALSE))
  # get the CI for everything
  paraN <- length(boot_res$t0)
  
  # percetile CI does not assume normality and has other good properties
  ind_fun <- function(index){boot.ci(boot_res, index = index, type = c("norm", "basic", "perc"))}
  # get the list of CI results
  ci_list <- map(1:paraN, ind_fun)
  # get values
  ci_value <- map(ci_list, "normal")
  
  # getting lower and upper limits
  ci_low <- flatten_dbl(map(ci_value, 2))
  ci_upr <- flatten_dbl(map(ci_value, 3))
  
  # getting names of the parameters
  Name <- c(names(fixef(model)), names(boot_res$t0)[-(1:length(names(fixef(model))))])
  
  # putting all togther
  res <- tibble(Name = Name, Est = as.numeric(boot_res$t0) , CI_L = ci_low, CI_U =  ci_upr)
  return(res)
  
}

Model1<-lmer(Total.Time.Spent.Questing~Life.Stage+Infection.Status+Day+(1|Combined.ID),data=TotaltimeQuesters)


new_res <- nonpara_boot(model = Model1, bootN = 1000)
summary(new_res)
new_res


#Model2<-lmer(Questing.Height.Average~Life.Stage+Infection.Status+Day+(1|Combined.ID),data=TotaltimeQuesters)


#new_res2 <- nonpara_boot(model = Model2, bootN = 1000)
#summary(new_res2)
#new_res2

#moderate repeatability is not significant in questing time and height bc both span 0
}
```





